"""add_users_table_and_user_id_to_data_tables

Revision ID: 746702ebe556
Revises: 0003
Create Date: 2026-04-26 15:13:32.548658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746702ebe556'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invex_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invex_users_email'), 'invex_users', ['email'], unique=True)
    op.add_column('invex_accounts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invex_accounts_user_id'), 'invex_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invex_accounts', 'invex_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('invex_equity_transactions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invex_equity_transactions_user_id'), 'invex_equity_transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invex_equity_transactions', 'invex_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('invex_holdings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invex_holdings_user_id'), 'invex_holdings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invex_holdings', 'invex_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('invex_mf_holdings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invex_mf_holdings_user_id'), 'invex_mf_holdings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invex_mf_holdings', 'invex_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('invex_portfolio_snapshots', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invex_portfolio_snapshots_user_id'), 'invex_portfolio_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invex_portfolio_snapshots', 'invex_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('invex_watchlist', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invex_watchlist_user_id'), 'invex_watchlist', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invex_watchlist', 'invex_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invex_watchlist', type_='foreignkey')
    op.drop_index(op.f('ix_invex_watchlist_user_id'), table_name='invex_watchlist')
    op.drop_column('invex_watchlist', 'user_id')
    op.drop_constraint(None, 'invex_portfolio_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_invex_portfolio_snapshots_user_id'), table_name='invex_portfolio_snapshots')
    op.drop_column('invex_portfolio_snapshots', 'user_id')
    op.drop_constraint(None, 'invex_mf_holdings', type_='foreignkey')
    op.drop_index(op.f('ix_invex_mf_holdings_user_id'), table_name='invex_mf_holdings')
    op.drop_column('invex_mf_holdings', 'user_id')
    op.drop_constraint(None, 'invex_holdings', type_='foreignkey')
    op.drop_index(op.f('ix_invex_holdings_user_id'), table_name='invex_holdings')
    op.drop_column('invex_holdings', 'user_id')
    op.drop_constraint(None, 'invex_equity_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_invex_equity_transactions_user_id'), table_name='invex_equity_transactions')
    op.drop_column('invex_equity_transactions', 'user_id')
    op.drop_constraint(None, 'invex_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_invex_accounts_user_id'), table_name='invex_accounts')
    op.drop_column('invex_accounts', 'user_id')
    op.drop_index(op.f('ix_invex_users_email'), table_name='invex_users')
    op.drop_table('invex_users')
    # ### end Alembic commands ###
